routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});
Route::resource('/home','HomeController');
// Route::resource('/villas','VillaController');

Route::Group(
    ['middleware'=>'auth'], function () {
        Route::resource('/orders','OrderController');  
        Route::resource('/addon','AddonController');
        Route::get('/doku/payment/{invoice}', 'DokuController@payment')->name('doku.payment');
    }
);

Route::post('/orders/doku/notify', 'DokuController@notify')->name('doku.notify');
Route::post('/orders/doku/redirect', 'DokuController@redirect')->name('doku.redirect');
Route::post('/orders/cart', 'OrderController@cart')->name('orders.cart');


Route::resource('/education_tours','EducationTourController');
Route::resource('/facilities','FacilityController');
Route::get('/booknow','OrderController@booknow')->name('orders.booknow');
Route::get('/meeting_room','FacilityController@meeting')->name('facilities.meeting');
Route::get('/camping_area','FacilityController@camping')->name('facilities.camping');
Route::get('/bundles/{id}','FacilityController@bundle')->name('bundles.show');
Route::get('login_out',function(){
    Auth::logout();
    return redirect('home');
})->name('logging');
Auth::routes();

// Route::get('/cus','HomeController@load_cus')->name('index.cus');
Route::get('/update','HomeController@load_cus')->name('load.cus');
Route::get('/bundle','FacilityController@bundle_index')->name('bundle.index');
Route::post('/update','HomeController@upd_cus')->name('upd.cus');

Route::post('/password','HomeController@upd_pass')->name('upd.pass');

Route::get('/password', function() {
    return view('profile._password');    
})->name('password');

Route::get('profile', function() {
    return view('profile.index');
})->name('profile');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/villas/{type}/show', 'VillaController@show')->name('villas.show');
Route::resource('/news','NewsController');
Route::get('/swimming_pool','HomeController@swimming_pool')->name('home.swimming_pool');

//Activies
Route::get('/activities','HomeController@activities')->name('activities');
Route::get('/{type}', 'VillaController@index')->name('villas.index');

app/Addon.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\carbon;
class Addon extends Model
{
    protected $guarded =[];
    protected $hidden = [
            'active','borrowed','limited','slug'];
    
    public function scopeActive($query)
   {
       return $query->where('active',1)->where('front_end',1);
   }
    public function available()
    {
        if($this->limited==1){
            return $this->stock-$this->borrowed;
        }
        return 99999;
    }
    public function detail_order()
    {
        return $this->morphMany('App\DetailOrder', 'item');
    }
    public function unit()
    {
        return $this->belongsTo('App\Unit', 'unit_id');
    }
    public function bundle_detail()
    {
        return $this->morphMany('App\BundleDetail', 'bundl');
    }
    public function folio()
    {
        return $this->morphMany('App\Folio', 'folio');
    }
    public function coupon_facility()
    {
        return $this->morphMany('App\CouponFacility', 'facs');
    }
    public function special_price()
    {
        return $this->morphMany('App\SpecialPrice', 'special');
    }
    public function custom_price()
    {
        return $this->morphMany('App\CustomPrice', 'price');
    }

    public function getActiveNameAttribute()
    {
        return $this->active==1 ? "Aktif" : "Tidak Aktif";
    }

    public function menu()
    {
        return $this->hasMany('App\Menu');
    }

public function getAddonTypeAttribute()
    {
    $text=["Tambahan","Makanan","Snack"];
    return $text[$this->type];
    }

    public function scopeFront($query)
    {
        return $query->where('front_end', '=' ,1);
    }
    public function scopeAddon($query)
    {
        return $query->where('type', '=' ,0);
    }

    public function scopeFood($query)
    {
        return $query->where('type', '=' ,1);
    }

    public function scopeSnack($query)
    {
        return $query->where('type', '=' ,2);
    }

    protected $appends = ['active_name'];

    public function calPrice($ammount=1,$disc=0,$stay=1,$custype=0){
        // return $custype;
        // $start= Carbon::createFromFormat("Y-m-d",$date);
        // $end = $start->addDays($dur);
        $total=0;
        // $vl=[];
        $total += $this->todayPrice($stay,$custype);
        // return $vl;
        
        $total *=$ammount;
        $total -= $total * $disc/100;
        return $total;
    }

    public function todayPrice($stay = 0, $custtype = 0){
        $cusp = SpecialPrice::where("special_id",$this->id)->where("special_type","LIKE","%Addon")->get();
        if(count($cusp) > 0){
            foreach($cusp as $cus){
                if($cus->customer_type_id==$custtype){
                    if($stay==0){
                        // if($dt->isWeekend())        
                        // {return $cus->no_stay_weekend_price;}
                        // else        
                        // {return $cus->no_stay_weekday_price;}
                        return $cus->no_stay_weekday_price;
                    }
                    else if($stay==1){
                        // if($dt->isWeekend())        
                        //     {return $cus->weekend_price;}
                        // else        
                        //     {return $cus->price;}
                            return $cus->price;
                    }
                }
            }
        }
        if($stay==0){
                return $this->no_stay_weekday_price;
        }
        return $this->price;
    }
}

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $guarded =[];

    public function addon()
    {
        return $this->BelongsTo('App\Addon','addon_id');
    }
    

    public function getitemLabelAttribute()
    {
        return json_decode($this->description);
    }


    public function setDescriptionAttribute($value)
    {
        $this->attributes['description'] = json_encode($value);
    }
    public function getDescriptionLabelAttribute()
    {
        $str="";
        foreach($this->item_label as $item){
            $str.=$item.", ";
        }
        
        return rtrim($str,", ");
    }
}

app/Http/Controllers/AddonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Facility;
use App\Customer;
use App\Order;
use App\DetailOrder;
use Auth;
use H;
use App\Folio;
use App\Bundle;
use App\DetailFacility;
use App\Addon;
use App\Menu;
use App\Invoice;
use App\DetailInvoice;

use DB; 
use Illuminate\Validation\ValidationException; 
use Illuminate\Support\Facades\Validator;
class AddonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $sessfacil=$request->session()->get('fasilitas',[]);
        $sessfoods=$request->session()->get('foods',[]);
        $sessaddons=$request->session()->get('addons', []);
        $facilitytoform=[];
        foreach($sessfacil as $facil){
            $facil=(object) $facil;
            $base_id=explode("-",$facil->id);
            if($base_id[0]=="B"){
            $facility = Bundle::find($base_id[1]);

            }
            else{
                $facility = Facility::find($base_id[1]);
                
            }
            $facilitytoform[]=['facility'=>$facility,'person'=>$facil->person,'unit'=>$facil->units,'total'=>$facil->total];
        }
        
        $foodtoform=[];
        if(count($sessfoods) >0){
             $sessfoods=(Object) $sessfoods;
            foreach($sessfoods->id as $i=>$foods){
                $flabel = "Pilih Menu";
                 if(strpos($foods,'|') === false){
                    $fmenu = Menu::find($foods);
                    if($fmenu)
                        $flabel = $fmenu->addon->name." - ".$fmenu->name;
                }
                else{
                    $ids=explode('|',$foods);
                    $fmenu = Menu::whereIn('id',$ids)->get();
                    if($ids[0]==$ids[1]){
                        $fmenu = Menu::find($ids[0]);
                        $flabel = $fmenu->addon->name." - ".$fmenu->name."(2)";
                    }
                    else{
                        $flabel = $fmenu[0]->addon->name." - ".$fmenu[0]->name.", ".$fmenu[1]->name;
                        $fmenu = Menu::find($ids[0]);
                    }
                }

                $foodtoform[]=['id'=>$foods,'label'=>$flabel,'food'=>$fmenu,'amount'=>$sessfoods->amount[$i],'time'=>$sessfoods->time[$i],'type'=>$sessfoods->type[$i],'total'=>$sessfoods->total[$i]];
            }
        }
       

        //  return $request->session()->get('bookings', 'default');
        $addons = Addon::addon()->active()->get();
        $meal = Addon::food()->with("menu")->active()->get();
        $snack = Addon::snack()->with("menu")->active()->get();

        $foods=[$meal,$snack];
        $customer = new Customer;
        $value = $request->session()->get('data', 'default');
        // return $value;
        $facility = $request->session()->get('facility', 'default');
        $type = $request->session()->get('type', 'default');
        $price = $request->session()->get('price', 'default');
        // return $type;
        // return $facility;
        if($type=="Bundle"){
            $facility = Bundle::find($facility);
        // return $facility;
            
        }
        else{
            $facility = Facility::find($facility);
            
        }
        // return $foods;

        $enddate = Carbon::createFromFormat('Y-m-d',$value['startdate'])->startOfDay();
        $enddate->addDays($value['duration']);
        //jenis(snack/makananan),Nama yang nampil di depan,sama hari atau esoknya( klo sama hari isi kosong klo hari besok nya isi 1), jam default

        $defaultmenu= array([0,'Lunch',0,'12:00',0],[1,'Coffe Break',0,'15:30',0],[0,'Dinner',0,'18:00',0],[0,'Breakfast',1,'07:00',0],[1,'Snack',1,'10:00',0]);
        $menu=json_decode(H::globs('menu',json_encode($defaultmenu)));
        $defaultlastdayMenu=array([0,'Lunch',1,'12:00',1]);
        $lastdayMenu=json_decode(H::globs('last_menu',json_encode($defaultlastdayMenu)));
        $price= array_fill(0, count($menu) * $value['duration'], 0);
        $tax = H::globs('tax','10')/100;
        $id=0;
        if(Auth::user()){
            $id=Auth::user()->customer_type_id;
        }
        $total = $facility->calPrice($value['startdate'],$value['duration'],$value['person'],0,1,$id);
        $tax *= $total;
        return view('addon.form',compact('facilitytoform','lastdayMenu','foodtoform','sessfoods','sessaddons','value','menu','addons','foods','tax','customer','enddate'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/addon/modals.blade.php
	<!-- Modal -->
	<div id="myModal1" class="modal fade" role="dialog">
		<div class="modal-dialog">

			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title pull-left">Pilih Snack</h4>

					<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			{{-- <input type="text" id="Search_All"> --}}
				{!! Form::hidden('', '', ['class'=>'id_pick']) !!}
				<div class="modal-body">
				<br>
				<div class="row">
					<div class="form-group col-md-6">
					{{ Form::label('paket','Paket Snack') }}
					{{ Form::select('paket', empty($foods[1]) ? array() : $foods[1]->pluck('name','id') ,0, ['class' => 'form-control select2 select2class snackselect', 'required']) }}
					
				</div>
				<div class="form-group col-md-6">
					{!! Form::hidden('', '', ['class'=>'snackprice']) !!}
					<h4><div style="margin-top:20px" id="snackprice">Rp.0,00</div></h4>
				</div>
				</div>
				
				@foreach($foods[1] as $f => $food)  
				@if (count($food->menu)>0)
				<br>
				<div class="row foption"  id="foodoption-{{ $food->id }}" style='display:none'>
					<div class="col-md-12">
					<h4>{{ $food->name }}</h4>
					</div>
						<div class="form-group col-md-6">
							{{ Form::label('col_name','Snack 1') }}
							{{ Form::select('col_name', empty($food->menu) ? array() : $food->menu->pluck('name','id') ,0, ['class' => 'form-control select2 select2class foodsnack1','id'=>'foodsnack1-'.$food->id, 'required']) }}
							@if ($errors->has('col_name'))
								<div class="help-block text-red">
									{{ $errors->first('col_name') }}
								</div>
							@endif
						</div>
						<div class="form-group col-md-6">
							{{ Form::label('col_name','Snack 2') }}
							{{ Form::select('col_name', empty($food->menu) ? array() : $food->menu->pluck('name','id') ,0, ['class' => 'form-control select2 select2class foodsnack2', 'id'=>'foodsnack2-'.$food->id, 'required']) }}
							@if ($errors->has('col_name'))
								<div class="help-block text-red">
									{{ $errors->first('col_name') }}
								</div>
							@endif
						</div>
				</div>
				@else
				<br>
				<div class="row foption" id="foodoption-{{ $food->id }}" style='display:none'>
					<div class="col-md-12">
						<h4><i>Menu Tidak Tersedia</i></h4>
					</div>
				</div>
				@endif
				
							@endforeach       
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-accent picksnackmenu" data-dismiss="modal" disabled>Pilih Menu</button>

				</div>
			</div>

		</div>
	</div>

	<div id="myModal0" class="modal fade" role="dialog" >
		<div class="modal-dialog">

			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title pull-left">Pilih Makanan</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			{{-- <input type="text" id="Search_All">	   --}}
				{!! Form::hidden('', '', ['class'=>'id_pick']) !!}
				<div class="modal-body">
					
				
				@foreach($foods[0] as $f => $food)  
				@if (count($food->menu)>0)

				<br>
				<div class="row">
					<div class="col-md-12">
				<h4>{{ $food->name }}</h4>
					</div>
					<div class="col-md-12">
						<table class="table">
							<thead>
							<tr>
								<th style="width: 20%;">Menu</th>
								{{-- <th style="width: 30%;">Harga</th> --}}
								<th style="width: 20%;">Harga</th>
								<th style="width: 30%;">Makanan</th>
								<th style="width: 30%;">Action</th>
							</tr>
							</thead>
							<tbody>         
								@foreach($food->menu as $k => $v)  
								<tr>
									<td>{{ $v->name }}</td>
									<td>{{ H::rupiah($food->price) }}</td>
									<td>{{ $v->description_label }}</td>
									<td><button data-dismiss="modal" data-price={{ $food->price}} data-name='{{ $food->name }} - {{ $v->name}}' id="btn-{{ $v->id }}" class="add_line btn btn-primary">Pilih Menu</button></td>
								</tr>     
								@endforeach        
							</tbody>
						</table>
					</div>
				</div>
				@endif
							@endforeach       
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>

	<div id="myModalFacility" class="modal fade" role="dialog" style="z-index:1151 !important;">
		<div class="modal-dialog modal-lg">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title pull-left">Tambah Fasilitas</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			{{-- <input type="text" id="Search_All">	   --}}

				<div class="modal-body" id="facilityBody">
				<div class="row">
									<div class="col-md-5">
											<div class="form-group col-md-12">
													{{ Form::label('jumlOrang','Jumlah Orang') }}
													{{ Form::number('jumlOrang',$value['person'], [ 'class' => 'form-control finput','id'=>'jumlOrg']) }}
													@if ($errors->has('jumlOrang'))
															<div class="help-block text-red">
																	{{ $errors->first('juml') }}
															</div>
													@endif
											</div>
											
									</div>   
									<div class="col-md-5">
											<div class="form-group col-md-12">
													{{ Form::label('jumlKam','Jumlah Unit') }}
													{{ Form::number('jumlKam',$value['unit'], [ 'class' => 'form-control finput' ,'id'=>'jumlKam']) }}
													@if ($errors->has('jumlKam'))
															<div class="help-block text-red">
																	{{ $errors->first('juml') }}
															</div>
													@endif
											</div>
									</div>    
									<div class="col-md-2">
											<div class="form-group col-md-12">
											</div>
											<div class="form-group col-md-12">
													<button class="btn btn-success searchfacil"> <span class="fa fa-search"></span></button>
											</div>
									</div>    
							</div>
							<table class="table myfacilitytable">
						<thead>
							<tr>
								<th style="width: 30%;" colspan="2">Fasilitas</th>
								{{-- <th style="width: 30%;">Harga</th> --}}
								<th style="width: 20%;">Harga/Hari</th>
								<th style="width: 5%;">Minimum</th>
								<th style="width: 5%;">Kapasitas</th>
								<th style="width: 10%;">Action</th>
							</tr>
							</thead>
							<tbody style="display:none;" id="tablefacilitytofill" class="animate-bottom">         
								<tr>
								</tr>
							</tbody>
						</table>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>