routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});
Route::resource('/home','HomeController');
// Route::resource('/villas','VillaController');

Route::Group(
    ['middleware'=>'auth'], function () {
        Route::resource('/orders','OrderController');  
        Route::resource('/addon','AddonController');
        Route::get('/doku/payment/{invoice}', 'DokuController@payment')->name('doku.payment');
    }
);

Route::post('/orders/doku/notify', 'DokuController@notify')->name('doku.notify');
Route::post('/orders/doku/redirect', 'DokuController@redirect')->name('doku.redirect');
Route::post('/orders/cart', 'OrderController@cart')->name('orders.cart');


Route::resource('/education_tours','EducationTourController');
Route::resource('/facilities','FacilityController');
Route::get('/booknow','OrderController@booknow')->name('orders.booknow');
Route::get('/meeting_room','FacilityController@meeting')->name('facilities.meeting');
Route::get('/camping_area','FacilityController@camping')->name('facilities.camping');
Route::get('/bundles/{id}','FacilityController@bundle')->name('bundles.show');
Route::get('login_out',function(){
    Auth::logout();
    return redirect('home');
})->name('logging');
Auth::routes();

// Route::get('/cus','HomeController@load_cus')->name('index.cus');
Route::get('/update','HomeController@load_cus')->name('load.cus');
Route::get('/bundle','FacilityController@bundle_index')->name('bundle.index');
Route::post('/update','HomeController@upd_cus')->name('upd.cus');

Route::post('/password','HomeController@upd_pass')->name('upd.pass');

Route::get('/password', function() {
    return view('profile._password');    
})->name('password');

Route::get('profile', function() {
    return view('profile.index');
})->name('profile');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/villas/{type}/show', 'VillaController@show')->name('villas.show');
Route::resource('/news','NewsController');
Route::get('/swimming_pool','HomeController@swimming_pool')->name('home.swimming_pool');

//Activies
Route::get('/activities','HomeController@activities')->name('activities');
Route::get('/{type}', 'VillaController@index')->name('villas.index');

app/Facility.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\DetailFacility;
use Carbon\carbon;
use App\CustomPrice;
use App\SpecialPrice;
class Facility extends Model
{
    protected $hidden = [
        'id','slug','link_embed', 'type_id','front_end','back_end','unit_name','code','created_at','updated_at','weekend_price','no_stay_weekend_price','no_stay_weekday_price','per_person'
    ];

    public function getidMorphAttribute()
    {
        return "F-".$this->id;
    }

   public function scopeActive($query)
   {
       return $query->where('back_end',1)->where('front_end',1);
   }
 

    public function gallery()
    {
        return $this->morphMany('App\Gallery', 'galleriable');
    }

    public function facilityType()
    {
        return $this->belongsTo('App\FacilityType', 'type_id');
    }
    public function facilityDetail()
    {
        return $this->hasMany('App\FacilityDetail', 'facility_id');
    }
    public function detailFacility()
    {
        return $this->hasMany('App\DetailFacility', 'facility_id');
    }
    public function special_price()
    {
    return $this->morphMany('App\SpecialPrice', 'special');
    }

    public function custom_price()
    {
    return $this->morphMany('App\CustomPrice', 'price');
    }

    
    protected $guarded =[];
    public function getunitLabelAttribute()
    {
        if($this->unit==1) {
            return "jam";
        }
        return "hari";
    }
    public function getUnitNameAttribute()
    {
        if($this->unit==1) {
            return "Jam";

        }
        else if($this->unit==2) {
            return "Hari";

        }
    }

        //Return array of prices with amount
    public function calDetPrice($date,$dur,$person=1,$disc=0,$stay=0,$custype=0){
        $arra=[];
        $start= Carbon::createFromFormat("Y-m-d",$date);
        $total=0;
        for($i=0;$i<$dur;$i++){
            $curdate = $start->format("Y-m-d");
            $json = json_encode($this->todayDetPrice($curdate,$stay,$custype));
            if(empty($arra[$json])){
                $arra=array_add($arra,$json,0);
            }
            $arra[$json]+=1;
            $start->addDays(1);
        }
        return $arra;
    }

     //Return price and name
    public function todayDetPrice($date,$stay=0,$custtype=0){
        $dt = Carbon::createFromFormat("Y-m-d",$date);
        $prices=0;
        $dayiso = $dt->format('N');
       
        $cusp = SpecialPrice::where("special_id",$this->id)->where("special_type","LIKE","%Facility")->get();
        if(count($cusp) > 0){
            foreach($cusp as $cus){
                if($cus->customer_type_id==$custtype){
                    if($stay==0){
                        if($dayiso >= 5)        
                        {return ["Special Price No Stay Weekend",$cus->no_stay_weekend_price];}
                        else        
                        {return ["Special Price No Stay Weekday",$cus->no_stay_weekday_price];}
                    }
                    else if($stay==1){
                        if($dayiso >= 5 )        
                            {return ["Special Price Weekend",$cus->weekend_price];}
                        else        
                            {return ["Special Price Weekday",$cus->price];}
                    }
                }
            }
        }
        if($stay==0){
            if($dayiso >= 5 )        
                {return ["No Stay Weekend",$this->no_stay_weekend_price];}
            else        
                {return ["No Stay Weekday",$this->no_stay_weekday_price];}
        }
        if(($dayiso >= 5) && $this->weekend_price!=null)        
                {return ["Weekend",$this->weekend_price]; }
        return ["Weekday",$this->price];
         $cusp = CustomPrice::whereDate("startdate","<=",$date)->whereDate("enddate",">=",$date)->where("price_id",$this->id)->where("price_type","LIKE","%Facility")->first();
        if($cusp)
            return ["Custom Price",$cusp->price];
    }

    

    public function calPrice($date,$dur,$person=1,$disc=0,$stay=1,$custype=0){
        // return $custype;
        $start= Carbon::createFromFormat("Y-m-d",$date);
        // $end = $start->addDays($dur);
        $total=0;
        // $vl=[];
        for($i=0;$i<$dur;$i++){
            $curdate = $start->addDays(1)->format("Y-m-d");
            $total += $this->todayPrice($curdate,$stay,$custype);
            // $vl=array_add($vl,$curdate,$this->todayPrice($curdate));
        }
        // return $vl;
        if($this->per_person==1 && $this->minimum>$person){
            $person = $this->minimum;
        }
        if($this->per_person==1)
            $total *=$person;                  
        $total -= $total * $disc/100;
        return $total;
    }

    public function todayPrice($date,$stay=0,$custtype=0){
        $dt = Carbon::createFromFormat("Y-m-d",$date);
        $cusp = CustomPrice::whereDate("startdate","<=",$date)->whereDate("enddate",">=",$date)->where("price_id",$this->id)->where("price_type","LIKE","%Facility")->first();
        if($cusp)
            return $cusp->price;
        $cusp = SpecialPrice::where("special_id",$this->id)->where("special_type","LIKE","%Facility")->get();
        if(count($cusp) > 0){
            foreach($cusp as $cus){
                if($cus->customer_type_id==$custtype){
                    if($stay==0){
                        if($dt->isWeekend())        
                        {return $cus->no_stay_weekend_price;}
                        else        
                        {return $cus->no_stay_weekday_price;}
                    }
                    else if($stay==1){
                        if($dt->isWeekend())        
                            {return $cus->weekend_price;}
                        else        
                            {return $cus->price;}
                    }
                }
            }
        }
                if($stay==0){
                    if($dt->isWeekend())        
                        {return $this->no_stay_weekend_price;}
                    else        
                        {return $this->no_stay_weekday_price;}
                }
        if($dt->isWeekend() && $this->weekend_price!=null)        
                {return $this->weekend_price;}
        return $this->price;
    }
    public function Available($date,$dur){
        $det = DetailFacility::where("facility_id",$this->id)->rentable($date,$dur)->get();
        return $det;
    }

    protected $appends =['unit_name','villa_image','id_morph'];

    public function detail_order()
    {
        return $this->morphMany('App\DetailOrder', 'item');
    }
    public function bundle_detail()
    {
        return $this->morphMany('App\BundleDetail', 'bundl');
    }

    public function coupon_facility()
    {
    return $this->morphMany('App\CouponFacility', 'facs');
	}
	
	public function getVillaImageAttribute()
    {
        if ($this->gallery->count() == 0) {
            return '/image/default-picture.png';
        }
        return '/image/'.$this->gallery[0]->image_path;
    }
	public function getlinkEmbedSrcLabelAttribute()
	{
		if($this->link_embed)
			return explode('"',explode(" ",$this->link_embed)[1])[1];
		return "";
	}
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use App\CustomSchedule;
use App\Facility;
use App\FacilityType;
use App\FacilityDetail;
use App\Gallery;
use App\Testimony;
use App\News;
use App\Category;
use Auth;
use App\Customer;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;
use Hash;
use App\User;
use App\Activity;
use App\Banner;
use App\BannerLocation;

class HomeController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index(Request $req)
    {
        // dd(session()->all());
        $bloc=BannerLocation::where('code','LIKE','atas')->first();
        $batas= Banner::where('banner_location_id',$bloc->id)->get();
        $type = FacilityType::pluck('name','id')->all();
        $allvilla = FacilityType::where('type','1')->pluck("id");            
        $villas = Facility::whereIn('type_id',$allvilla)->active()->limit(6)->get();
        $facility = Facility::where('type_id','>=',3)->active()->get();
        $sp = Gallery::where('kode','SP')->first();
        $testi = Testimony::orderBy("id","DESC")->limit(2)->get();
        $newss = News::query();
        $newss=$newss->orderBy('id','DESC')->limit(3)->get();
        $cats = Category::all()->pluck("name","id");
        $list=array();
        // return $facility[0]->gallery;
        return view('home.home',compact('list','testi','type','villas','facility'))
        ->with("types","facilities")
        ->with('news', $newss)
        ->with('cats', $cats)
        ->with('batas', $batas)
        ->with('sp', $sp);
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        //
    }
    
    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        //
    }
    
    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id)
    {
        //
    }
    
    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        //
    }
    
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id)
    {
        //
    }
    
    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        //
    }
    public function load_cus(Request $req)
    {
        $customer = Auth::user();
        return view('profile._form')->with('customer',$customer);
    }
    
    public function upd_cus(Request $req)
    {
        $cus = Customer::find(Auth::user()->id);
        $cus->fill($req->all());
        $cus->save();
        return redirect()->route('profile');    
        // return $cus;
    }
    public function upd_pass(Request $req)
    {
        // return $req;
        
        $errors =[];
        $cus = Customer::find(Auth::user()->id);
        //    return bcrypt($req->old_pass)." AnD ".$cus->password;  
           if (!Hash::check($req->old_pass, Auth::user()->password)) {
            $errors=array_add($errors,"old_pass","Password Lama Tidak sesuai");            
                
            }   

        if(strlen($req->new_pass)<6) {
            $errors=array_add($errors,"new_pass","Panjang minimum password adalah 6");                                    
        }
        if($req->new_pass!=$req->conf_pass) {
            $errors=array_add($errors,"conf_pass","Password baru tidak cocok dengan password konfirmasi");                        
        }

            if(count($errors)>0) {
                throw ValidationException::withMessages($errors);
            }

            $user = User::find(Auth::user()->id)
                ->update(
                    ['password'=> Hash::make($req->new_pass)]
                );
            return redirect()->route('profile');
    }

    public function activities()
    {
        $activities = Activity::all()->sortby('sort');
        // dd($activities);
        return view('home.activities',compact('activities'));
    }


    public function swimming_pool()
    {
        $sp = Gallery::where('kode','SP')->first();
        return view('home.swimming_pool')->with('sp', $sp);
    }

}

resources/views/home/activities.blade.php
@extends('layouts.app')
@push('styles')
<style>
</style>
@endpush

@section('content')

<section class="title-section bg-light-grey0">
	<div class="container">
		<div class="row justify-content-md-center text-center">
			<div class="col-md-9">
				<h2 class="title dark-color">Aktivitas</h2>
			</div>  
		</div>
	</div>
</section>
<section class="content-section activities">
	<div class="container">
		<div class="card-columns"> <!-- Ini yang membuat jadi masonry, bawa an nya bootstrap 4-->
			@foreach($activities as $activity)
			<div class="card">
				@if ($activity->image)
				<img class="card-img-top" src="{{ env('BACKEND_HOST').'image/'.$activity->image }}" alt="Card image cap">
				@endif
				@if ($activity->title || $activity->description )
				<div class="card-body">
					@if ($activity->title)<h5 class="card-title">{{ $activity->title }}</h5>@endif
					@if ($activity->description)<p class="card-text">{!! $activity->description !!}</p>@endif
				</div>
				@endif
			</div>
			@endforeach
		</div>
	</div>



</section>

@endsection

resources/views/home/bundle.blade.php
@extends('layouts.app')
@push('styles')
<style>

</style>
@endpush
@section('content')

<section class="title-section bg-light-grey0">
  <div class="container">
   <div class="row justify-content-md-center text-center">
     <div class="col-md-9">
       <h2 class="title dark-color">{{ $facility->name }}</h2>
     </div>  
   </div>
 </div>
</section>


<section class="content-section">
  <div class='container'>
    <div class="row">
      <div class="col-md-7">    

        <div id="myCarousel" class="carousel slide" style="text-align: center" width="100%"  height="550px" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            @php($i=0)      
            @foreach($gallery as $gal)    
            <li data-target="#myCarousel" data-slide-to="{{$i}}" class="{{ $i==0 ? 'active' : '' }}"></li>
            @php($i++)
            @endforeach
          </ol>
          <div class="carousel-inner">
            @php($i=0)
            @foreach($gallery as $gal)      
            <div class="item {{ $i==0 ? 'active' : '' }}">
              @php($i++)        
              <img class="items img-fluid w-100" src="{{ env('BACKEND_HOST').'image/'.$gal->image_path }}" alt="{{ $facility->name }}">
            </div>
            @endforeach
          </div>
          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        
      </div>
      <div class="col-md-5 facility-content">

        <div class="facility-detail mb-1">
          <h5 class="detail-title accent-color">Bundlings Include</h5>
          <ul class="ul-facility-detail">
          @php($i=0)
          @foreach($facility->bundle_detail as $fd)
            
              @php($i++)
              <li>
                <i class="accent-color pr-2" data-toggle="tooltip" data-placement="top" title="{{$fd->nameLabel }}"></i> <!-- Jangan lupa ganti dengan font awesome dari db -->
                {{$fd->nameLabel }} {{$fd->value}}
              </li>
              
          @endforeach
          </ul>
        </div>

        <div class="facility-price mb-1">
          <p>Start from <span class="strong">{!! H::rupiah($facility->weekend_price) !!}</span>/day</p>
        </div>

        <div class="row">
          <div class='col-md-12'>      
            <h4>{!!$facility->description !!}</h4>
            @if($facility->minimum > 0 && $facility->maximum > 0)
            <h4>Minimum order untuk fasilitas ini adalah {{$facility->minimum }} dan kapasitas maksimumnya adalah {{$facility->capacity}} orang.</h4>
            @elseif ($facility->maximum > 0)
            <h4>Tida ada minimum order untuk fasilitas ini dan kapasitas maksimumnya adalah {{$facility->capacity}} orang.</h4>
            @endif
            <h5>Waktu Check-in pk 14.00 </br>Waktu Checkout pk 12.00 <br/>(<em>berlaku untuk semua akomodasi dan fasilitas</em>)</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="content-section">
  <div class='container'>
    @if($facility->type_id == 3)
    <div class="row justify-content-md-center">
      <div class="col-md-10">
       <h3 class="dark-color text-center mb-5">Meeting Room Set-Up</h2>
       <img class="img-fluid" src="{{asset('image/mr-setup-diagram.png')}}" alt="meeting-room-setup"/>
      </div>
    </div>
    @endif
  </div>
</section>





<section class="check-booking bg-light-grey">
  <div class="container">
   <div class="row justify-content-md-center text-center">
     <div class="col-md-9">
      <div class="title-plus-text">
        <h3 class="sub-title playfair-font font-italic grey-color">Cara mudah untuk</h3>
        <h2 class="title font-weight-light dark-color">Melakukan <span class="accent-color font-weight-bold ">Booking </span></h2>
        <p class="caption-content roboto-font ">Cukup isi kolom di bawah ini, dan pilih ruangan yang Anda inginkan melalui sistem booking online kami.</p>
      </div>
    </div>
    <div class="col-md-10 mt-5">
      {!! Form::open(['route' => ['bundle.index'], 'method'=>'GET', 'enctype'=>'multipart/form-data','role' => 'form']) !!}

      <div class="row">
        <div class="col-6 col-md-2 px-less"  style="margin-bottom: 10px;">
          {!! Form::date('startdate',date("Y-m-d"), ['placeholder' => 'Mulai Tanggal','class'=> 'form-control','required' => 'required']) !!}
        </div>
        <div class="col-6 col-md-2 px-less"  style="margin-bottom: 10px;">
          {!! Form::number('duration',null, ['placeholder' => 'Durasi (hari)','class'=> 'form-control','required' => 'required']) !!}
        </div>
        <div class="col-6 col-md-2 px-less"  style="margin-bottom: 10px;">
          {!! Form::number('person',null, ['placeholder' => 'Jumlah Tamu/Peserta','class'=> 'form-control personformfilter','required' => 'required']) !!}
        </div>
         <div class="col-6 col-md-2 px-less"  style="margin-bottom: 10px;">
          {!! Form::number('unit',null, ['placeholder' => 'Jumlah Unit','class'=> 'form-control unitformfilter','required' => 'required']) !!}
        </div>
        <div class="col-6 col-md-3 px-less"  style="margin-bottom: 10px;">
          {!! Form::select('type',$type, 4,['placeholder' => 'Tipe','class'=> 'form-control select2','required' => 'required', 'disabled'=>'true']) !!}


          {!! Form::hidden('id',$facility->id,['class'=> 'form-control' ]) !!}
        </div>
      </div>
      <div class="row justify-content-md-center btn-cek-ketersediaan">        
        <div class="col-md-4">
          <button type="submit" class="btn btn-accent btn-big searchbutton">Cek Ketersediaan</button>
        </div>
      </div>
      {!! Form::close() !!}

    </div>
  </div>
</div>
</section>




@stop


@push('scripts')
@include('layouts._script')
@endpush

resources/views/home/educationtour.blade.php
@extends('layouts.app')
@push('styles')
<style>
</style>
@endpush

@section('content')

<section class="title-section bg-light-grey0">
  <div class="container">
   <div class="row justify-content-md-center text-center">
     <div class="col-md-9">
       <h2 class="title dark-color">{{$education_tour->title}}</h2>
     </div>  
   </div>
 </div>
</section>


<section class="content-section">
  <div class='container'>
    <div class="row align-items-center">
      <div class="col-md-7">         
        <div id="myCarousel" class="carousel slide" style="text-align: center" width="100%"  height="550px" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            @php($i=0)      
            @foreach($education_tour->gallery as $gal)    
            <li data-target="#myCarousel" data-slide-to="{{$i}}" class="{{ $i==0 ? 'active' : '' }}"></li>
            @php($i++)
            @endforeach
          </ol>
          <div class="carousel-inner">
            @php($i=0)
            @foreach($education_tour->gallery as $gal)      
            <div class="item {{ $i==0 ? 'active' : '' }}">
              @php($i++)        
              <img class="items img-fluid w-100" src="{{ env('BACKEND_HOST').'image/'.$gal->image_path }}" alt="{{ $education_tour->name }}">
            </div>
            @endforeach
          </div>
          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

      <div class="col-md-5 facility-content">

        <div class="facility-description mb-1" style="height: 100%">
        {!!$education_tour->description !!}
        </div>

        
      </div>
    </div>
  </div>
</section>




@stop

resources/views/home/villa.blade.php
@extends('layouts.app')
@push('styles')
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
<style>

</style>
@endpush

@section('content')

<section class="title-section bg-light-grey0">
  <div class="container">
   <div class="row justify-content-md-center text-center">
     <div class="col-md-9">
       <h2 class="title dark-color">{{ $villa->name }}</h2>
     </div>  
   </div>
 </div>
</section>


<section class="content-section">
  <div class='container'>
    <div class="row">
      <div class="col-md-7">         
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            @php($i=0)      
            @foreach($villa->gallery as $gal)    
            <li data-target="#carouselExampleIndicators" data-slide-to="{{$i}}" class="{{ $i==0 ? 'active' : '' }}"></li>
            @php($i++)
            @endforeach
          </ol>
          <div class="carousel-inner">
            @php($i=0)
            @foreach($villa->gallery as $gal)      
            <div class="carousel-item {{ $i==0 ? 'active' : '' }}">
              @php($i++)        
              <img class="d-block w-100" src="{{ env('BACKEND_HOST').'image/'.$gal->image_path }}" alt="{{ $villa->name }}">
            </div>
            @endforeach
            </div> 
            <a class="carousel-control-prev d-lg-none" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next d-lg-none "  href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

        @if($villa->link_embed_src_label!="")
          <iframe class="mt-5" src="{{ $villa->link_embed_src_label }}" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>    
        @endif
        </div>
      

      <div class="col-md-5 facility-content">
        <div class="facility-detail mb-1">
          <h5 class="detail-title accent-color">Fasilitas yang Tersedia</h5>
          <ul class="ul-facility-detail">
          @php($i=0)
          @foreach($villa->facilityDetail as $fd)
              @php($i++)
              <li>
                <i class="{{$fd->facility_attribute->icon}} accent-color pr-2" data-toggle="tooltip" data-placement="top" title="{{$fd->facility_attribute->name}}"></i> <!-- Jangan lupa ganti dengan font awesome dari db -->
                <span class="facility-include">{{$fd->facility_attribute->name}} : {{$fd->value}}</span>
              </li>
          @endforeach
          </ul>
        </div>
        <div class="facility-price mb-1">
          <p><span class="strong">{!! H::rupiah($villa->weekend_price) !!}</span>/hari</p>
        </div>
        <div class="facility-description mb-1">
        <h4>{!!$villa->description!!}</h4>
        <br/>
            @if($villa->minimum > 0 && $villa->maximum > 0)
            <h4>Minimum order untuk akomodasi ini adalah {{$villa->minimum }} dan kapasitas maksimumnya adalah {{$villa->capacity}} orang.</h4>
            @elseif($villa->maximum > 0)
            <h4>Tida ada minimum order untuk akomodasi ini dan kapasitas maksimumnya adalah {{$villa->capacity}} orang.</h4>
            @endif
            <h5>Waktu Check-in pk 14.00 </br>Waktu Checkout pk 12.00 <br/>(<em>berlaku untuk semua akomodasi dan fasilitas</em>)</h5>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="check-booking bg-light-grey">
  <div class="container">
   <div class="row justify-content-md-center text-center">
     <div class="col-md-9">
      <div class="title-plus-text">
        <h3 class="sub-title playfair-font font-italic grey-color">Cara mudah untuk</h3>
        <h2 class="title font-weight-light dark-color">Melakukan <span class="accent-color font-weight-bold ">Booking </span></h2>
        <p class="caption-content roboto-font ">Cukup isi kolom di bawah ini, dan pilih ruangan yang Anda inginkan melalui sistem booking online kami.</p>
      </div>
    </div>
    <div class="col-md-10 mt-5">
      {!! Form::open(['route' => ['facilities.index'], 'method'=>'GET', 'enctype'=>'multipart/form-data','role' => 'form']) !!}

      <div class="row">
        <div class="col-6 col-md-2 px-less"  style="margin-bottom: 10px;">
          {!! Form::date('startdate',date("Y-m-d"), ['placeholder' => 'Mulai Tanggal','class'=> 'form-control','required' => 'required']) !!}
        </div>
        <div class="col-6 col-md-2 px-less"  style="margin-bottom: 10px;">
          {!! Form::number('duration',null, ['placeholder' => 'Durasi (hari)','class'=> 'form-control','required' => 'required']) !!}
        </div>
        <div class="col-6 col-md-2 px-less"  style="margin-bottom: 10px;">
          {!! Form::number('person',null, ['placeholder' => 'Jumlah Tamu/Peserta','class'=> 'form-control personformfilter','required' => 'required']) !!}
        </div>

        <div class="col-6 col-md-2 px-less"  style="margin-bottom: 10px;">
          {!! Form::number('unit',null, ['placeholder' => 'Jumlah Unit','class'=> 'form-control unitformfilter','required' => 'required']) !!}
        </div>

        <div class="col-6 col-md-3 px-less"  style="margin-bottom: 10px;">
          {!! Form::select('type',$type, $villa->type_id,['placeholder' => 'Tipe','class'=> 'form-control select2','required' => 'required', 'disabled'=>'true']) !!}

          {!! Form::hidden('id',$villa->id,['class'=> 'form-control']) !!}
        </div>
      </div>
      <div class="row justify-content-md-center btn-cek-ketersediaan">        
        <div class="col-md-4">
          <button type="submit" class="btn btn-accent btn-big searchbutton">Cek Ketersediaan</button>
        </div>
      </div>
      {!! Form::close() !!}

    </div>
  </div>
</div>
</section>


@endsection

@push('scripts')
@include('layouts._script')

  <script type="text/javascript">
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

@endpush