routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});
Route::resource('/home','HomeController');
// Route::resource('/villas','VillaController');

Route::Group(
    ['middleware'=>'auth'], function () {
        Route::resource('/orders','OrderController');  
        Route::resource('/addon','AddonController');
        Route::get('/doku/payment/{invoice}', 'DokuController@payment')->name('doku.payment');
    }
);

Route::post('/orders/doku/notify', 'DokuController@notify')->name('doku.notify');
Route::post('/orders/doku/redirect', 'DokuController@redirect')->name('doku.redirect');
Route::post('/orders/cart', 'OrderController@cart')->name('orders.cart');


Route::resource('/education_tours','EducationTourController');
Route::resource('/facilities','FacilityController');
Route::get('/booknow','OrderController@booknow')->name('orders.booknow');
Route::get('/meeting_room','FacilityController@meeting')->name('facilities.meeting');
Route::get('/camping_area','FacilityController@camping')->name('facilities.camping');
Route::get('/bundles/{id}','FacilityController@bundle')->name('bundles.show');
Route::get('login_out',function(){
    Auth::logout();
    return redirect('home');
})->name('logging');
Auth::routes();

// Route::get('/cus','HomeController@load_cus')->name('index.cus');
Route::get('/update','HomeController@load_cus')->name('load.cus');
Route::get('/bundle','FacilityController@bundle_index')->name('bundle.index');
Route::post('/update','HomeController@upd_cus')->name('upd.cus');

Route::post('/password','HomeController@upd_pass')->name('upd.pass');

Route::get('/password', function() {
    return view('profile._password');    
})->name('password');

Route::get('profile', function() {
    return view('profile.index');
})->name('profile');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/villas/{type}/show', 'VillaController@show')->name('villas.show');
Route::resource('/news','NewsController');
Route::get('/swimming_pool','HomeController@swimming_pool')->name('home.swimming_pool');

//Activies
Route::get('/activities','HomeController@activities')->name('activities');
Route::get('/{type}', 'VillaController@index')->name('villas.index');

resources/views/bookings/create-v1.blade.php
@extends('layouts.app')
@push('styles')
<style>
	body{
		background-color: rgb(230,230,230);
	}
	.navbar{
		background-color: rgb(400,4000,400);
	}
	.container{
		margin-top:30px;
	}
	.box {
		margin-bottom:10px;
		width:100%;
	    background: #fff;
	    border-radius: 4px;
	    -webkit-box-sizing: border-box;
	    box-sizing: border-box;
	    display: inline-block;
		position: relative;
		    padding: 27px 25px 34px;
	    border-radius: 3px;
	    border: 1px solid #dedede;
	    border-left-width: 2px;
	}
	.pr{
		margin-bottom:0px;
	}
	.info-booking {
	    line-height: 1.5;
	    font-weight: 300;
	    margin-top: 7px;
	    font-size: 12px;
	    color: #bbbaba;
	}
/*._1Hwni {
    background-color: rgba(0,0,0,.12);
    border: none;
    height: 1px;
    margin: 0;
    margin-top: -1px;
}*/
/*.cqAhQ {
    padding: 16px 32px;
    background-color: #fafafa;
}*/

/*.chk{
	margin-left:20px;
	margin-top:30px;
}*/
.booking-price {
	text-align: right;
    vertical-align: top;
	
}
/*._1TPg2 .booking-price, ._1TPg2 .Xnbsb {
    vertical-align: top;
    font-weight: 500;
}*/
</style>
@endpush
@section('content')
{{--  {{ Auth::user()}}  --}}
<section class="title-section bg-light-grey0">
	<div class="container">
		<div class="row justify-content-md-center text-center">
			<div class="col-md-9">
				<h2 class="title dark-color">Booking Orders</h2>
			</div>  
		</div>
	</div>
</section>
<section class="content-section booking-order">
	<div class="container" >
	<div class="row">
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-12">
				<h3>Isi Data</h3>
				
				<div class="box" style="border-left-color: rgb(27, 160, 226);">
				{{--  {{ json_encode(Auth::user()) }}  --}}
					<div class="box-header">
					</div>
					<div class="box-body">
						{!! Form::model($customer, ['route' => ['orders.store'], 'method'=>'POST','enctype'=>'multipart/form-data', 'role' => 'form']) !!}
						
					<div class="row">
						<div class="col-md-12">
							<label>Nama Peminjam</label>
							{!! Form::text('guest_name', $customer->name ? $customer->name :Auth::user()->name , ['class'=> 'form-control','required' => 'required']) !!}
							<div class=""><div class="info-booking"></div><div class="info-booking">As in Passport/Official ID Card (without title/special characters)</div></div>
						</div>
						<br>
						<br>
						<div class="col-md-12">
							<label>Phone Number</label>
							{!! Form::number('guest_phone', $customer->phone ? $customer->phone :Auth::user()->phone, ['class'=> 'form-control','required' => 'required']) !!}
							<div class=""><div class="info-booking"></div><div class="info-booking">e.g. +62812345678, for Country Code (+62) and Mobile No. 0812345678</div></div>
						</div>
						<br>
						<br>
						<div class="form-group col-md-12">
							{{ Form::label('description','Catatan') }}
							{{ Form::text('description',"", ['class' => 'form-control']) }}
							<div class=""><div class="info-booking"></div><div class="info-booking">Please write in English or in villas local language.</div></div>							
							@if ($errors->has('description'))
								<div class="help-block text-red">
									{{ $errors->first('description') }}
								</div>
							@endif
						</div>
						
						
					</div>
					</div>
					<br>
						
				</div>
			</div>
			<br>
			<div class="col-md-12">
					<h3>Price</h3>
					<div class="box pr"  style="border-left-color: rgb(27, 160, 226);">
					<div class="box-header">
					
					</div>
					<div class="box-body">
						<div class="row">
							<div class="col-md-12">
								<div class="row">
									<div class="col-md-12">
										<h3> {{$facility->facilityType->name}}</h3>
									</div>
								</div>
								<div class="row">								
									<div class="col-md-6">
										<h5> {{ $facility->name."(".$value['duration']." Night)"}} </h5>
									</div>
									<div class="col-md-6  booking-price">
										<h5>{{ H::rupiah($facility->calPrice($value['startdate'],$value['duration'],$value['person'])) }}</h5>										
									</div>
									<div class="col-md-6">
										<h5> {{ "Tax"}} </h5>
									</div>
									<div class="col-md-6  booking-price">
										<h5>{{ H::rupiah($tax) }}</h5>										
									</div>
									
								</div>
							</div>
						</div>
					</div>
					
				</div>
				<div class="box">
						<div class="row">
							<div class="col-md-6">
								<h4>Total</h4>
							</div>
							<div class="col-md-6 booking-price">
								<h4>{{ H::rupiah($facility->calPrice($value['startdate'],$value['duration'],$value['person'])+$tax) }}</h4>
							</div>
						</div>
					</div>
			</div>


		</div>

	</div>
	<br>
	<br>
	<div class="col-md-4" style="margin-top:43px">
		<div class="box" >
			<div class="box-header">
				<center><h3>Booking Detail</h3></center>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-md-12">
						<div class="row">
							<div class="col-md-6">	
								<senter><img width="100%"src="{{ env('BACKEND_HOST').$facility->villa_image }}"/></senter>						
							</div>
							<div class="col-md-6">	
								<h6>{{ $facility->name}}</h6>
							</div>
						</div>
					</div>
					<hr>
					<br>
					<div class="col-md-12">
						<div class="row">
							{{--  <div class="col-md-12"><center><h3>{{$facility->name}}</h3></center></div>  --}}
					<div class="col-md-6 pull-left">Duration of Stay</div>
					<div class="col-md-6 pull-right" style="text-align: right;">{{$value['duration']}} Night</div>
					<div class="col-md-6 pull-left">Check In</div>
					<div class="col-md-6 pull-right" style="text-align: right;">{{$value['startdate']}}</div>
					<div class="col-md-6 pull-left">Check Out</div>
					<div class="col-md-6 pull-right" style="text-align: right;">{{$enddate->format("Y-m-d")}}</div>
					<div class="col-md-6 pull-left">Room Type</div>
					<div class="col-md-6 pull-right" style="text-align: right;">{{$facility->facilityType->name}}</div>
					<div class="col-md-6 pull-left">Guest per Room</div>
					<div class="col-md-6 pull-right" style="text-align: right;">{{$facility->capacity}} Guests</div>
					
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	</div>
	
	<br>
	<br>
	<div class="row">
		<div class="col-md-12">
					<div class="row">
						<div class="col-md-12">				
							{{ Form::submit('Lanjutkan', ['class' => 'btn btn-primary','style'=>'width:100%']) }}
						</div>
					</div>
				</div>
			{{ Form::close() }}
		</div>
	<br>
	<br>
	<br>
	<br>
	</div>
</section>
@stop

resources/views/bookings/create.blade.php
	@extends('layouts.app')
	@push('styles')
	<style>
	.detail{
margin-bottom: -10px !important;
font-size: 0.9rem !important;
color: rgb(168, 222, 48);
	}	
	</style>
	@endpush
	@section('content')
	{{--  {{ Auth::user()}}  --}}
	<section class="title-section bg-light-grey0">
		<div class="container">
			<div class="row justify-content-md-center text-center">
				<div class="col-md-9">
					<h2 class="title dark-color">Proses Booking</h2>
				</div>  
			</div>
		</div>
	</section>
	<section class="content-section booking-order">
		<div class="container">
			<div class="row mb-4 justify-content-md-center">

				<div class="col-md-8 ">
					{!! Form::model($customer, ['route' => ['orders.store'], 'method'=>'POST','enctype'=>'multipart/form-data', 'role' => 'form']) !!}
					<h3 class="mt-4">Data Booking</h3>
				
					<div class="form-group row">
						<div class="col-md-6">
							<label for="guest_name">Nama</label>
							{!! Form::text('guest_name', $customer->name ? $customer->name :Auth::user()->name , ['class'=> 'form-control','required' => 'required']) !!}
							<div class="info-booking">Nama sesuai Passport/KTP (Tanpa Gelar / Karakter Khusus)</div>
						</div>
						<div class="col-md-6">
							<label for="guest_phone">Nomor Telepon</label>
							{!! Form::number('guest_phone', $customer->phone ? $customer->phone :Auth::user()->phone, ['class'=> 'form-control','required' => 'required']) !!}
							<div class="info-booking">e.g. +62812345678, untuk Kode Negara (+62) dan Nomor Telepon 08112345678</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<label  class="detail">Durasi</label>
							<p>{{ $value['duration']}} hari</p>
						</div>
						<div class="col-md-3">
							<label  class="detail">Check In </label>
							<p>{{ H::tanggal(Carbon\carbon::parse($value['startdate'])->format("w-d-n-Y")) }}</p>
						</div>
						<div class="col-md-3">
							<label class="detail">Check Out </label>
							<p>{{ H::tanggal($enddate->format("w-d-n-Y")) }}</p>
						</div>
						<div class="col-md-3">
							<label  class="detail">Jumlah Tamu / Peserta </label>
							<p>{{$value['person']}} orang</p>
						</div>
					</div>
					<div class="form-group row">
						<div class="col-md-12">
							<label for="description">Catatan</label>
							{{ Form::text('description',"", ['class' => 'form-control']) }}
							<div class="info-booking">Tolong menggunakan bahasa Inggris atau Indonesia</div>
						</div>
					</div>

					<h3 class="mt-4">Pesanan Anda</h3>
					@if ($errors->has('name'))
					<p style="color: red">{{ $errors->first('name') }}</p>
							@endif
					<table class="table table-bordered table-order">
						<thead>
							<th class="text-uppercase">Pesanan</th>
							<th class="text-uppercase">jumlah</th>
							<th class="text-uppercase text-right">Total</th>
						</thead>
						<tbody>
							@php($total=0)
							@foreach ($floops as $i=>$facilitys)
							<tr>
								<td>{{ $facilitys['facility']->name." (".$value['duration']." hari)"}}</td>
								@php($subtotal=$facilitys['facility']->calPrice($value['startdate'],$value['duration'],$facilitys['person'])*$facilitys['unit'])
								@php($total+=$subtotal)
								<td>{{ $facilitys['unit']." Unit x ".$facilitys['person']." Orang" }}</td>
								<td class="text-right">{{ H::rupiah($subtotal) }}</td>
							</tr>
							@endforeach
							@foreach ($afloops as $i=>$food)
							<tr>
								@if(count($food['food'])>1)
									<td>{{ $food['food'][0]->addon->name." - ".$food['food'][0]->name.", ".$food['food'][1]->name}}</td>
									@php($subtotal=$food['food'][0]->addon->price*$food['amount'])
									@php($total+=$subtotal)
									<td>{{ $food['amount']." Porsi" }}</td>	
								@elseif(count($food['food'])>0)
									@if( strpos($food['originidfood'],'|') === false)
									<td>{{ $food['food']->addon->name." - ".$food['food']->name }}</td>
									@else
									<td>{{ $food['food']->addon->name." - ".$food['food']->name."(2)" }}</td>
									@endif
									@php($subtotal=$food['food']->addon->price*$food['amount'])
									@php($total+=$subtotal)
									<td>{{ $food['amount']." Porsi" }}</td>
								@endif
							

								<td class="text-right">{{ H::rupiah($subtotal) }}</td>
							</tr>
							@endforeach
							@foreach ($aloops as $i=>$facilitys)
							<tr>
								<td>{{ $facilitys['addon']->name}}</td>
								@php($subtotal=$facilitys['addon']->price*$facilitys['amount'])
								@php($total+=$subtotal)
								<td>{{ $facilitys['amount']." Buah" }}</td>
								<td class="text-right">{{ H::rupiah($subtotal) }}</td>
							</tr>
							@endforeach
							<tr style="background-color:#efefef;"> 
								<td class="font-weight-bold" colspan="2">Total</td>
								<td class="text-right font-weight-bold">{{ H::rupiah($total) }}</td>
							</tr>
							
						</tbody>
					</table>
					<div class="payment-method">
						<h6 class="payment-ins">Silahkan memilih metode pembayaran yang ingin digunakan.</h6>
						<div class="form-check">
						<label class="form-check-label">
							<input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
							Transfer Bank
						</label>
						</div>
						<div class="form-check">
						<label class="form-check-label">
							<input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
							Kartu Kredit via DOKU
						</label>
						</div>
						<div class="form-check">
						<label class="form-check-label">
							<input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios3" value="option3">
							Alfamart via DOKU
						</label>
						</div>
					</div>
					
				</div>
				{{-- <div class="col-md-4 booking-detail">
					<h5>Detail Booking</h5>
					<div class="box">
					<img width="100%" class="img-fluid" src="{{ env('BACKEND_HOST').$facility->villa_image }}"/>
					<h5 class="mt-2">{{ $facility->name}}</h5>
					<div class="row">
						
						<div class="col-8 col-md-7">
							<p>Durasi :</p>
						</div>
						<div class="col-4 col-md-5 text-right">
							<p>{{$value['duration']}} hari</p>
						</div>
						<div class="col-8 col-md-7">
							<p>Check In : </p>
						</div>
						<div class="col-4 col-md-5 text-right">
							<p>{{$value['startdate']}}</p>
						</div>
						<div class="col-8 col-md-7">
							<p>Check Out : </p>
						</div>
						<div class="col-4 col-md-5 text-right">
							<p>{{$enddate->format("Y-m-d")}}</p>
						</div>
						@if(session()->get('type', 'default') == "Facility")
						<div class="col-8 col-md-7">
							<p>Tipe : </p>
						</div>
						<div class="col-4 col-md-5 text-right">
							<p>{{$facility->facilityType->name}}</p>
						</div>
						@endif
						<div class="col-8 col-md-7">
							<p>Jumlah Tamu / Peserta : </p>
						</div>
						<div class="col-4 col-md-5 text-right">
							<p>{{$value['person']}} orang</p>
						</div>
						
					</div>
					</div>
				</div> --}}
			</div>
			
			<div class="row justify-content-end">
				<div class="col-md-2 col-lg-2 col-8 selanjutnya ">				
					{{ Form::submit('Selanjutnya', ['class' => 'btn btn-block btn-accent btn-small']) }}
				</div>
			</div>
				{{ Form::close() }}
			<div class="row justify-content-start" style="margin-top: -39px;">
				<div class="col-md-2 col-lg-2 col-8" >	
					<a href="{{ route('addon.create') }}" class="btn btn-block btn-small btn-warning goback">< Kembali</a>
				</div>
			</div>
		
			</div>
		</div>
	</section>
	@stop

@push('scripts')
<script>
</script>
@endpush

resources/views/bookings/index.blade.php
@extends('layouts.app')
@push('styles')
<style>
</style>
@endpush

@section('content')
<section class="title-section bg-light-grey0">
	<div class="container">
		<div class="row justify-content-md-center text-center">
			<div class="col-md-9">
				<h2 class="title dark-color"> Tersedia untuk Anda</h2>
			</div>  
		</div>
	</div>
</section>
<section class="content-section booking-list">
	<div class="container" >
		@if(!$request->has('id'))
		@php($list=$nlist)
		@php($prices=$nprices)
			<!-- <center> <h1>Available {{$ident}}</h1></center>-->
		@endif

		@if(count($list)==0 && count($nlist)>0)
			<!-- <center> <h1>Available {{$ident}}</h1></center>	 -->
		@elseif($request->has('id'))
			<!-- <center> <h1>Available {{$ident}}</h1></center>	 -->
		@endif	

		@if(count($list)==0 && count($nlist)==0) <!-- Alternatif tdk ada juga-->
			<center> <h4>Maaf, saat ini tidak ada {{ strtolower($ident) }} yang dapat dipesan untuk {{ $person }} orang dalam {{ $unit }} {{$ident}}</h4></center>	
			<center> <h5><a href={{ route('villas.index',['type'=>2]) }}>Mohon mengganti kriteria pencarian anda.</a></h5></center>	
		@elseif(count($list)==0)
			<center> <h4>Maaf, saat ini {{ strtolower($ident) }} yang anda pilih tidak tersedia pada waktu dan durasi yang anda cari.</h4></center>					
			<center> <h5><a href={{ route('villas.index',['type'=>2]) }}>Mohon mengganti kriteria pencarian anda.</a></h5></center>	
			<center> <h5>atau anda dapat memilih rekomendasi {{ strtolower($ident) }} lain dari kami dibawah ini: </h5></center>						
		@endif

		@php($i=0)
		@foreach($list as $keys => $l)
			<div class="row justify-content-md-center align-items-center mb-5" >
				@php($i++)	
				<div class="col-12 col-md-4">
					<img class="img-fluid" src="{{ env('BACKEND_HOST').$l->villa_image }}"  class="center-cropped">
				</div>
				<div class="col-12 col-md-4 content">

					<h4 class="facility-name dark-color text-uppercase">{{$l->name}}</h4>
					<h3 class="facility-price dark-color">{{H::rupiah($prices[$keys])}}/hari</h3>
					@if($l->capacity>0)
					<p class="facility-guest grey-color">{{$l->capacity}} orang</p>
					@endif
					<a href="{{route('orders.booknow', ['data' => $request->all(),'facility' => $l->id_morph ,'type'=>$type ,'price'=>$prices[$keys]])}}" class="btn btn-small btn-dark">Pesan Sakarang
					</a>
				</div>
				<div class="col-12 col-md-2 content">
					<a class="view-more dark-color" href="{{route('villas.show',['villa'=>$l->slug])}}">Informasi Lebih lanjut</a>
				</div>
			</div>
		@endforeach
</div>
</section>

@if(count($nlist)>0 && $request->has('id'))
<section class="content-section bg-light-grey2 booking-list">	

	<div class="container" >
		<div class="row">
			
			<div class="col-md-12">
				@if(count($list)==0)		
				<!-- <center> <h1>Available {{$ident}}</h1></center>	 -->
				@else
				<!-- <center> <h1>Also Available {{$ident}}</h1></center>	 -->
				@endif
				@php($i=0)
				@foreach($nlist as $keys => $l)
				<div class="row justify-content-md-center align-items-center mb-5" >
				@php($i++)	
				<div class="col-12 col-md-4">
					<img class="img-fluid" src="{{ env('BACKEND_HOST').$l->villa_image }}"  class="center-cropped">
				</div>
				<div class="col-12 col-md-4 content">

					<h4 class="facility-name dark-color text-uppercase">{{$l->name}}</h4>
					<h3 class="facility-price dark-color">{{H::rupiah($nprices[$keys])}}/hari</h3>
					@if($l->capacity>0)
					<p class="facility-guest grey-color">{{$l->capacity}} orang</p>
					@endif
					<a href="{{route('orders.booknow', ['data' => $request->all(),'facility' => $l->id_morph ,'type'=>$type ,'price'=>$nprices[$keys]])}}" class="btn btn-small btn-dark">Pesan Sakarang
					</a>
				</div>
				<div class="col-12 col-md-2 content">
					<a class="view-more dark-color" href="{{route('villas.show',['villa'=>$l->slug])}}">Informasi Lebih lanjut</a>
				</div>
			</div>
				@endforeach
			</div>
		</div>
	</div>
</section>
@endif
@stop

resources/views/bookings/thankyou.blade.php
@extends('layouts.app')
@push('styles')
  
<style>
	
</style>
@endpush
@section('content')
{{--  {{ Auth::user()}}  --}}
<section class="title-section bg-light-grey0">
    <div class="container">
        <div class="row justify-content-md-center text-center">
            <div class="col-md-9">
                <h2 class="title dark-color">Booking Orders</h2>
            </div>  
        </div>
    </div>
</section>
<section class="content-section booking-order">
    <div class="container">
        <h3>Order Details</h3>
    	<div class="row">
        	<div class="col-md-7">		
        		<table class="table table-bordered table-order">
                    <thead>
                        <th class="text-uppercase">Product</th>
                        <th class="text-uppercase text-right">Total</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ $facility->name." (".$value['duration']." night) "}}</td>
                            <td class="text-right">{{ H::rupiah($facility->calPrice($value['startdate'],$value['duration'],$value['person'])) }}</td>
                        </tr>
                        <tr>
                            <td>Tax</td>
                            <td class="text-right">{{ H::rupiah($tax) }}</td>
                        </tr>
                        <tr>
                            <td>Payment Method</td>
                            <td class="text-right">Credit Card via DOKU ???</td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold">Total</td>
                            <td class="text-right font-weight-bold">{{ H::rupiah($facility->calPrice($value['startdate'],$value['duration'],$value['person'])+$tax) }}</td>
                        </tr>
                    </tbody>
                </table>
        	</div>

        	<div class="col-md-5">
                <div class="well">
                    <p class="accent-color">Thank you. Your order has been received.</p>
                    <ul>
                        <li>Order number: <span class="font-weight-normal">17145</span></li>
                        <li>Date: <span class="font-weight-normal">May 7, 2018</span></li>
                        <li>Total: <span style="color: black; font-weight: 500;">{{ H::rupiah($facility->calPrice($value['startdate'],$value['duration'],$value['person'])+$tax) }}</span></li>
                        <li>Payment Method: <span class="font-weight-normal">Credit Card via DOKU ???</span></li>
                    </ul>
                </div>
        	</div>
        </div>
    </div>
</section>
@stop

@push('scripts')
<script>
$(document).ready(function(){
	$('[data-toggle="tooltip"]').tooltip(); 

// Set the date we're counting down to
var countDownDate = new Date("{{ Carbon\Carbon::now()->addDays(H::globs('expiry'))->format("M j, Y H:i:s") }}").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

    // Get todays date and time
    var now = new Date().getTime();
    
    // Find the distance between now an the count down date
    var distance = countDownDate - now;
    
    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
    // Output the result in an element with id="demo"
    document.getElementById("demo").innerHTML = "Complete your payment within "+days + " days " + hours + " hours "
    + minutes + " minutes " + seconds + " seconds ";
    
    // If the count down is over, write some text 
    if (distance < 0) {
        clearInterval(x);
        document.getElementById("demo").innerHTML = "EXPIRED";
    }
}, 1000);
});
</script>
@endpush