routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});
Route::resource('/home','HomeController');
// Route::resource('/villas','VillaController');

Route::Group(
    ['middleware'=>'auth'], function () {
        Route::resource('/orders','OrderController');  
        Route::resource('/addon','AddonController');
        Route::get('/doku/payment/{invoice}', 'DokuController@payment')->name('doku.payment');
    }
);

Route::post('/orders/doku/notify', 'DokuController@notify')->name('doku.notify');
Route::post('/orders/doku/redirect', 'DokuController@redirect')->name('doku.redirect');
Route::post('/orders/cart', 'OrderController@cart')->name('orders.cart');


Route::resource('/education_tours','EducationTourController');
Route::resource('/facilities','FacilityController');
Route::get('/booknow','OrderController@booknow')->name('orders.booknow');
Route::get('/meeting_room','FacilityController@meeting')->name('facilities.meeting');
Route::get('/camping_area','FacilityController@camping')->name('facilities.camping');
Route::get('/bundles/{id}','FacilityController@bundle')->name('bundles.show');
Route::get('login_out',function(){
    Auth::logout();
    return redirect('home');
})->name('logging');
Auth::routes();

// Route::get('/cus','HomeController@load_cus')->name('index.cus');
Route::get('/update','HomeController@load_cus')->name('load.cus');
Route::get('/bundle','FacilityController@bundle_index')->name('bundle.index');
Route::post('/update','HomeController@upd_cus')->name('upd.cus');

Route::post('/password','HomeController@upd_pass')->name('upd.pass');

Route::get('/password', function() {
    return view('profile._password');    
})->name('password');

Route::get('profile', function() {
    return view('profile.index');
})->name('profile');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/villas/{type}/show', 'VillaController@show')->name('villas.show');
Route::resource('/news','NewsController');
Route::get('/swimming_pool','HomeController@swimming_pool')->name('home.swimming_pool');

//Activies
Route::get('/activities','HomeController@activities')->name('activities');
Route::get('/{type}', 'VillaController@index')->name('villas.index');

resources/views/layouts/_footer.blade.php
<footer class="footer">
	<section class="container footer-in">
		<div class="row">
			<div class="col-md-4">
				<h5 class="sub-title">Tentang IOC</h5>
				<p class="content">Dikenal dengan lingkungan hijau dan semangat edukasinya, IOC berkomitmen untuk memberikan pengalaman menyenangkan bagi Anda dalam mempererat hubungan dengan alam dan grup Anda. </p>
				<p class="content mb-0"><span class="accent-color">Telp:</span> 0888 0155 5921</p>
				<p class="content mb-0" style="margin-left:35px"> 0888 0155 5912</p>
				<p class="content mb-0"><span class="accent-color">Email:</span> utc_trawas@yahoo.com</p>
				<p class="content footerem"> utc@ubaya.ac.id</p>
				<p class="content"><span class="accent-color">Alamat:</span> Jl. Udayana, Trawas, Jawa Timur</p>
			</div>
			<div class="col-md-4">
				<h5 class="sub-title">Artikel</h5>
				<ul class="content list-unstyled">                          
    				@foreach($latest as $latest_news)
					<li>
	                	<a class="accent-color" href="{{route('news.show',['id'=>$latest_news->slug]) }}" title="{{ $latest_news->title }}">{{ $latest_news->title}}</a>
	                </li>					
					@endforeach
				</ul>
			</div>
			<div class="col-md-4">
				<h5 class="sub-title">Info Terbaru</h5>

				<p class="content">Jangan lewatkan penawaran menarik dari IOC dengan mendaftarkan email Anda pada kolom di bawah ini. </p>
				<div class="content">
					<!-- Begin MailChimp Signup Form -->
					<div id="mc_embed_signup">
						<form action="https://ubaya.us18.list-manage.com/subscribe/post?u=032071854c6a9a9766a9d2908&amp;id=3a7d791e8e" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
							<div id="mc_embed_signup_scroll">

								<div class="mc-field-group row justify-content-between">
									<div class=" col-sm-7 col">
									<input type="email" value="" name="EMAIL" class="required email form-control" id="mce-EMAIL" placeholder="Alamat Email">
									</div>
									<div class=" col-sm-5 col">
									<input type="submit" value="Kirim" name="subscribe" id="mc-embedded-subscribe" class="button btn btn-accent btn-block" style="text-transform: capitalize;font-size: 14px;">
									</div>
								</div>

								<div id="mce-responses" class="clear">
									<div class="response" id="mce-error-response" style="display:none"></div>
									<div class="response" id="mce-success-response" style="display:none"></div>
								</div>    
								<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
								<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_032071854c6a9a9766a9d2908_3a7d791e8e" tabindex="-1" value=""></div>
								
							</div>
						</form>
					</div>

					<!--End mc_embed_signup-->
				</div>
			</div>
		</div>		
	</section>
	<section class="footbot">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<div class="footer-navi">
						<span class="accent-color">Integrated Outdoor Campus </span> © Copyright 2018	
					</div>
				</div>
				<div class="col-md-6">
					<div class="footer-navi floatright">
						Developed by Luxodev	
					</div>
				</div>
			</div>
		</div>
	</section>
</footer>


<!-- Jquery -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

  	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{{--  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>  --}}
<!-- Bootstrap-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5b836495afc2c34e96e7ec90/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

@stack('scripts')

resources/views/layouts/_head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
<!-- Bootstrap css -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!-- Custom css -->
<link rel="stylesheet" type="text/css" href="{{ asset('css/custom.css') }}" />
<!-- Font Awesome -->
{{--  <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>  --}}
{{-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> --}}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  {{-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> --}}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<!-- <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"> -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

<!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127524853-3"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-127524853-3');
  </script>
  <style>
    .footerem{
      margin-left:45px;
    }
    @media only screen and (min-width: 0px) {
      .footerem{
        margin-left:45px;
      }
    }
    @media only screen and (min-width: 768px) {
      .footerem{
        margin-left:0px;
      }
    }
    @media only screen and (min-width: 992px) {
      .footerem{
        margin-left:45px;
      }
    }
    
  </style>
@stack('styles')

resources/views/layouts/_navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light ioc-navbar">
  <a class="navbar-brand" href="{{ route('home')}}"><img class="img-responsive" src="{{ asset('/image/ioc_utc_upc.png') }}"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ route('home')}}">Beranda <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('villas.index',['type'=>'rooms'])}}">Penginapan</a>
      </li>


      @foreach(H::nonvilla() as $vils)
      <li class="nav-item">
            <a class="nav-link" href="{{ route('villas.index',['type'=>$vils->slug])}}">{{$vils->name}}</a>            
      </li>      
      @endforeach

      <li class="nav-item">
        <a class="nav-link" href="{{ route('activities') }}" >Aktivitas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('news.index') }}">Artikel</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('education_tours.index') }}">Eduwisata</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto pull-right">
      {{--  <li class="nav-item active">
        <a class="nav-link" href="#"><i class="fa fa-user"></i></a>
      </li>  --}}
        @if (Route::has('login'))
                    @auth
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{Auth::user()->name}}
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('profile') }}">Profil</a>                            
                        <a class="dropdown-item" href="{{ route('logging') }}">Keluar</a>    
                        {{--  <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>  --}}
                      </div>
                  </li>            
                    @else
                    <li class="nav-item">                    
                        <a class="nav-link" href="{{ route('login') }}">Masuk</a>
                    </li>
                    <li class="nav-item">                  
                        <a class="nav-link"  href="{{ route('register') }}">Daftar</a>
                    </li>
                    @endauth
            @endif
      </li>
    </ul>
    
  </div>
</nav>

resources/views/layouts/_script.blade.php
<script>
    $('.unitformfilter, .personformfilter').on('keyup change', function(e){
        var unit=isNaN(parseInt($('.unitformfilter').val())) ? 1: parseInt($('.unitformfilter').val());
        var person=isNaN(parseInt($('.personformfilter').val())) ? 1: parseInt($('.personformfilter').val());
        if(unit>person){
            $('.searchbutton').attr("disabled", true);
        }
        else{
            $('.searchbutton').removeAttr("disabled");
        }
    });
</script>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
  @include("layouts._head")
</head>
<body >
  @include("layouts._navbar")
  @yield('content')
  @include('layouts._footer')
</body>
</html>